    SELECT
    (SELECT COUNT(*) 
     FROM STAGE_EMPLOYEE) AS TOTAL_RECORDS_RECEIVED,

    (SELECT COUNT(*) - COUNT(DISTINCT EMPLOYEE_ID)
     FROM STAGE_EMPLOYEE) AS DUPLICATE_RECORDS_IDENTIFIED,

    (SELECT COUNT(*)
     FROM TGT_EMPLOYEE) AS GOLDEN_RECORDS_CREATED,

    (SELECT COUNT(*)
     FROM STAGE_EMPLOYEE
     WHERE EMPLOYEE_ID IS NULL
        OR FIRST_NAME IS NULL
        OR LAST_NAME IS NULL
        OR EMAIL IS NULL
        OR EMAIL NOT LIKE '%@%.%'
        OR PHONE IS NULL
        OR LENGTH(REGEXP_REPLACE(PHONE,'[^0-9]','')) <> 10
    ) AS REJECTED_OR_INVALID_RECORDS;











