CREATE DATABASE EMPLOYEE_DB;
create schema DBO;


SELECT CURRENT_DATABASE(), CURRENT_SCHEMA();

CREATE OR REPLACE FILE FORMAT FF_EMPLOYEE_CSV
TYPE = CSV
FIELD_DELIMITER = ','
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
TRIM_SPACE = TRUE
EMPTY_FIELD_AS_NULL = TRUE
NULL_IF = ('NULL', '');

CREATE OR REPLACE STAGE STG_EMPLOYEE_FILES
FILE_FORMAT = FF_EMPLOYEE_CSV;

show stages;

LIST @STG_EMPLOYEE_FILES;