CREATE OR REPLACE TABLE STAGE_EMPLOYEE
(
    EMPLOYEE_ID STRING,
    FIRST_NAME STRING,
    LAST_NAME STRING,
    EMAIL STRING,
    PHONE STRING,
    DEPARTMENT STRING,
    CITY STRING,
    SOURCE_SYSTEM STRING
);
INSERT INTO STAGE_EMPLOYEE
SELECT
    EMP_ID        AS EMPLOYEE_ID,
    FIRST_NAME    AS FIRST_NAME,
    LAST_NAME     AS LAST_NAME,
    EMAIL         AS EMAIL,
    PHONE         AS PHONE,
    DEPARTMENT    AS DEPARTMENT,
    CITY          AS CITY,
    'HRM'        AS SOURCE_SYSTEM
FROM HRM;

INSERT INTO STAGE_EMPLOYEE
SELECT
    EMPLOYEE_CODE                 AS EMPLOYEE_ID,
    SPLIT_PART(FULL_NAME,' ',1)   AS FIRST_NAME,
    SPLIT_PART(FULL_NAME,' ',2)   AS LAST_NAME,
    EMAIL                         AS EMAIL,
    PHONE                         AS PHONE,
    DEPARTMENT                    AS DEPARTMENT,
    NULL                          AS CITY,
    'PAYROLL'                     AS SOURCE_SYSTEM
FROM PAYROLL;

INSERT INTO STAGE_EMPLOYEE
SELECT
    USER_ID        AS EMPLOYEE_ID,
    FIRST_NAME     AS FIRST_NAME,
    LAST_NAME      AS LAST_NAME,
    EMAIL          AS EMAIL,
    NULL           AS PHONE,
    NULL           AS DEPARTMENT,
    LOCATION       AS CITY,
    'ACTIVEDIRECTORYY' AS SOURCE_SYSTEM
FROM ACTIVEDIRECTORYY;

INSERT INTO STAGE_EMPLOYEE
SELECT
    EMP_NO                      AS EMPLOYEE_ID,
    SPLIT_PART(NAME,' ',1)      AS FIRST_NAME,
    SPLIT_PART(NAME,' ',2)      AS LAST_NAME,
    EMAIL                       AS EMAIL,
    MOBILE                      AS PHONE,
    NULL                        AS DEPARTMENT,
    CITY                        AS CITY,
    'CRM'                       AS SOURCE_SYSTEM
FROM CRM;

SELECT*FROM STAGE_EMPLOYEE;

SELECT
    SOURCE_SYSTEM,
    COUNT(*) AS RECORD_COUNT
FROM STAGE_EMPLOYEE
GROUP BY SOURCE_SYSTEM
ORDER BY SOURCE_SYSTEM;




TRUNCATE TABLE STAGE_EMPLOYEE;
SELECT COUNT(*) FROM STAGE_EMPLOYEE;
SELECT COUNT(*) FROM STAGE_EMPLOYEE;

SELECT
SOURCE_SYSTEM,
COUNT(*) AS RECORD_COUNT
FROM STAGE_EMPLOYEE
GROUP BY SOURCE_SYSTEM
ORDER BY SOURCE_SYSTEM;

Select * from STAGE_EMPLOYEE ORDER BY EMPLOYEE_ID ASC;
