CREATE OR REPLACE TABLE TGT_EMPLOYEE
(
    EMPLOYEE_ID  STRING,
    FIRST_NAME STRING,
    LAST_NAME STRING,
    FULL_NAME STRING,
    EMAIL STRING,
    PHONE STRING,
    LOCATION STRING,
    DEPARTMENT STRING
    
);


INSERT INTO TGT_EMPLOYEE

WITH cleaned AS (
    SELECT
        EMPLOYEE_ID,
        NULLIF(TRIM(FIRST_NAME), '')  AS FIRST_NAME,
        NULLIF(TRIM(LAST_NAME), '')   AS LAST_NAME,
        NULLIF(TRIM(EMAIL), '')       AS EMAIL,
        NULLIF(TRIM(PHONE), '')       AS PHONE,
        NULLIF(TRIM(DEPARTMENT), '')  AS DEPARTMENT,
        NULLIF(TRIM(CITY), '')        AS CITY,
        CASE SOURCE_SYSTEM
            WHEN 'HRMS'    THEN 1   
            WHEN 'PAYROLL' THEN 2
            WHEN 'CRM'     THEN 3
            ELSE 4
        END AS SRC_PRIORITY
    FROM STAGE_EMPLOYEE
),


fn AS (   -- FIRST_NAME
    SELECT EMPLOYEE_ID, FIRST_NAME,
           ROW_NUMBER() OVER (PARTITION BY EMPLOYEE_ID ORDER BY CNT DESC, MIN_PRI ASC) AS RN
    FROM (
        SELECT EMPLOYEE_ID, FIRST_NAME, COUNT(*) AS CNT, MIN(SRC_PRIORITY) AS MIN_PRI
        FROM cleaned
        WHERE FIRST_NAME IS NOT NULL
        GROUP BY EMPLOYEE_ID, FIRST_NAME
    ) t
),

ln AS (   -- LAST NAME
    SELECT EMPLOYEE_ID, LAST_NAME,
           ROW_NUMBER() OVER (PARTITION BY EMPLOYEE_ID ORDER BY CNT DESC, MIN_PRI ASC) AS RN
    FROM (
        SELECT EMPLOYEE_ID, LAST_NAME, COUNT(*) AS CNT, MIN(SRC_PRIORITY) AS MIN_PRI
        FROM cleaned
        WHERE LAST_NAME IS NOT NULL
        GROUP BY EMPLOYEE_ID, LAST_NAME
    ) t
),

em AS (   -- EMAIL
    SELECT EMPLOYEE_ID, EMAIL,
           ROW_NUMBER() OVER (PARTITION BY EMPLOYEE_ID ORDER BY CNT DESC, MIN_PRI ASC) AS RN
    FROM (
        SELECT EMPLOYEE_ID, EMAIL, COUNT(*) AS CNT, MIN(SRC_PRIORITY) AS MIN_PRI
        FROM cleaned
        WHERE EMAIL IS NOT NULL
        GROUP BY EMPLOYEE_ID, EMAIL
    ) t
),

ph AS (   -- PHONE
    SELECT EMPLOYEE_ID, PHONE,
           ROW_NUMBER() OVER (PARTITION BY EMPLOYEE_ID ORDER BY CNT DESC, MIN_PRI ASC) AS RN
    FROM (
        SELECT EMPLOYEE_ID, PHONE, COUNT(*) AS CNT, MIN(SRC_PRIORITY) AS MIN_PRI
        FROM cleaned
        WHERE PHONE IS NOT NULL
        GROUP BY EMPLOYEE_ID, PHONE
    ) t
),

dp AS (   -- DEPARTMENT
    SELECT EMPLOYEE_ID, DEPARTMENT,
           ROW_NUMBER() OVER (PARTITION BY EMPLOYEE_ID ORDER BY CNT DESC, MIN_PRI ASC) AS RN
    FROM (
        SELECT EMPLOYEE_ID, DEPARTMENT, COUNT(*) AS CNT, MIN(SRC_PRIORITY) AS MIN_PRI
        FROM cleaned
        WHERE DEPARTMENT IS NOT NULL
        GROUP BY EMPLOYEE_ID, DEPARTMENT
    ) t
),

ct AS (   -- CITY
    SELECT EMPLOYEE_ID, CITY,
           ROW_NUMBER() OVER (PARTITION BY EMPLOYEE_ID ORDER BY CNT DESC, MIN_PRI ASC) AS RN
    FROM (
        SELECT EMPLOYEE_ID, CITY, COUNT(*) AS CNT, MIN(SRC_PRIORITY) AS MIN_PRI
        FROM cleaned
        WHERE CITY IS NOT NULL
        GROUP BY EMPLOYEE_ID, CITY
    ) t
),

ids AS (
    SELECT DISTINCT EMPLOYEE_ID FROM cleaned
)

-- ---------- final master record: one row per EMPLOYEE_ID ----------
SELECT
    i.EMPLOYEE_ID,
    fn.FIRST_NAME,
    ln.LAST_NAME,
    fn.FIRST_NAME || ' ' || ln.LAST_NAME AS FULL_NAME,
    em.EMAIL,
    ph.PHONE,
    dp.DEPARTMENT,
    ct.CITY
FROM ids i
LEFT JOIN fn ON fn.EMPLOYEE_ID = i.EMPLOYEE_ID AND fn.RN = 1
LEFT JOIN ln ON ln.EMPLOYEE_ID = i.EMPLOYEE_ID AND ln.RN = 1
LEFT JOIN em ON em.EMPLOYEE_ID = i.EMPLOYEE_ID AND em.RN = 1
LEFT JOIN ph ON ph.EMPLOYEE_ID = i.EMPLOYEE_ID AND ph.RN = 1
LEFT JOIN dp ON dp.EMPLOYEE_ID = i.EMPLOYEE_ID AND dp.RN = 1
LEFT JOIN ct ON ct.EMPLOYEE_ID = i.EMPLOYEE_ID AND ct.RN = 1
ORDER BY i.EMPLOYEE_ID;

select* from TGT_EMPLOYEE

show tables;CREATE OR REPLACE TABLE TGT_EMPLOYEE
(
    EMPLOYEE_ID  STRING,
    FIRST_NAME STRING,
    LAST_NAME STRING,
    FULL_NAME STRING,
    EMAIL STRING,
    PHONE STRING,
    LOCATION STRING,
    DEPARTMENT STRING
    
);


INSERT INTO TGT_EMPLOYEE

WITH cleaned AS (
    SELECT
        EMPLOYEE_ID,
        NULLIF(TRIM(FIRST_NAME), '')  AS FIRST_NAME,
        NULLIF(TRIM(LAST_NAME), '')   AS LAST_NAME,
        NULLIF(TRIM(EMAIL), '')       AS EMAIL,
        NULLIF(TRIM(PHONE), '')       AS PHONE,
        NULLIF(TRIM(DEPARTMENT), '')  AS DEPARTMENT,
        NULLIF(TRIM(CITY), '')        AS CITY,
        CASE SOURCE_SYSTEM
            WHEN 'HRMS'    THEN 1   
            WHEN 'PAYROLL' THEN 2
            WHEN 'CRM'     THEN 3
            ELSE 4
        END AS SRC_PRIORITY
    FROM STAGE_EMPLOYEE
),

-- ---------- repeat the same "majority vote" pattern for each column ----------

fn AS (   -- FIRST_NAME
    SELECT EMPLOYEE_ID, FIRST_NAME,
           ROW_NUMBER() OVER (PARTITION BY EMPLOYEE_ID ORDER BY CNT DESC, MIN_PRI ASC) AS RN
    FROM (
        SELECT EMPLOYEE_ID, FIRST_NAME, COUNT(*) AS CNT, MIN(SRC_PRIORITY) AS MIN_PRI
        FROM cleaned
        WHERE FIRST_NAME IS NOT NULL
        GROUP BY EMPLOYEE_ID, FIRST_NAME
    ) t
),

ln AS (   -- LAST NAME
    SELECT EMPLOYEE_ID, LAST_NAME,
           ROW_NUMBER() OVER (PARTITION BY EMPLOYEE_ID ORDER BY CNT DESC, MIN_PRI ASC) AS RN
    FROM (
        SELECT EMPLOYEE_ID, LAST_NAME, COUNT(*) AS CNT, MIN(SRC_PRIORITY) AS MIN_PRI
        FROM cleaned
        WHERE LAST_NAME IS NOT NULL
        GROUP BY EMPLOYEE_ID, LAST_NAME
    ) t
),

em AS (   -- EMAIL
    SELECT EMPLOYEE_ID, EMAIL,
           ROW_NUMBER() OVER (PARTITION BY EMPLOYEE_ID ORDER BY CNT DESC, MIN_PRI ASC) AS RN
    FROM (
        SELECT EMPLOYEE_ID, EMAIL, COUNT(*) AS CNT, MIN(SRC_PRIORITY) AS MIN_PRI
        FROM cleaned
        WHERE EMAIL IS NOT NULL
        GROUP BY EMPLOYEE_ID, EMAIL
    ) t
),

ph AS (   -- PHONE
    SELECT EMPLOYEE_ID, PHONE,
           ROW_NUMBER() OVER (PARTITION BY EMPLOYEE_ID ORDER BY CNT DESC, MIN_PRI ASC) AS RN
    FROM (
        SELECT EMPLOYEE_ID, PHONE, COUNT(*) AS CNT, MIN(SRC_PRIORITY) AS MIN_PRI
        FROM cleaned
        WHERE PHONE IS NOT NULL
        GROUP BY EMPLOYEE_ID, PHONE
    ) t
),

dp AS (   -- DEPARTMENT
    SELECT EMPLOYEE_ID, DEPARTMENT,
           ROW_NUMBER() OVER (PARTITION BY EMPLOYEE_ID ORDER BY CNT DESC, MIN_PRI ASC) AS RN
    FROM (
        SELECT EMPLOYEE_ID, DEPARTMENT, COUNT(*) AS CNT, MIN(SRC_PRIORITY) AS MIN_PRI
        FROM cleaned
        WHERE DEPARTMENT IS NOT NULL
        GROUP BY EMPLOYEE_ID, DEPARTMENT
    ) t
),

ct AS (   -- CITY
    SELECT EMPLOYEE_ID, CITY,
           ROW_NUMBER() OVER (PARTITION BY EMPLOYEE_ID ORDER BY CNT DESC, MIN_PRI ASC) AS RN
    FROM (
        SELECT EMPLOYEE_ID, CITY, COUNT(*) AS CNT, MIN(SRC_PRIORITY) AS MIN_PRI
        FROM cleaned
        WHERE CITY IS NOT NULL
        GROUP BY EMPLOYEE_ID, CITY
    ) t
),

ids AS (
    SELECT DISTINCT EMPLOYEE_ID FROM cleaned
)

SELECT
    i.EMPLOYEE_ID,
    fn.FIRST_NAME,
    ln.LAST_NAME,
    fn.FIRST_NAME || ' ' || ln.LAST_NAME AS FULL_NAME,
    em.EMAIL,
    ph.PHONE,
    dp.DEPARTMENT,
    ct.CITY
FROM ids i
LEFT JOIN fn ON fn.EMPLOYEE_ID = i.EMPLOYEE_ID AND fn.RN = 1
LEFT JOIN ln ON ln.EMPLOYEE_ID = i.EMPLOYEE_ID AND ln.RN = 1
LEFT JOIN em ON em.EMPLOYEE_ID = i.EMPLOYEE_ID AND em.RN = 1
LEFT JOIN ph ON ph.EMPLOYEE_ID = i.EMPLOYEE_ID AND ph.RN = 1
LEFT JOIN dp ON dp.EMPLOYEE_ID = i.EMPLOYEE_ID AND dp.RN = 1
LEFT JOIN ct ON ct.EMPLOYEE_ID = i.EMPLOYEE_ID AND ct.RN = 1
ORDER BY i.EMPLOYEE_ID;

select* from TGT_EMPLOYEE

show tables;